// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4Xirudr6Zu3xjx5eYPbxPMCX5vTG5k-M',
    appId: '1:588898600407:web:5742ea6570c75012b1b792',
    messagingSenderId: '588898600407',
    projectId: 'social-app-5c79b',
    authDomain: 'social-app-5c79b.firebaseapp.com',
    storageBucket: 'social-app-5c79b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhynYzwBpZyzqZyN2QxoaUgtlCUIoQUBo',
    appId: '1:588898600407:android:1e8b72220330a324b1b792',
    messagingSenderId: '588898600407',
    projectId: 'social-app-5c79b',
    storageBucket: 'social-app-5c79b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb5Nu9mtB1A6f9fff9sbUWqhFKlSCN3y0',
    appId: '1:588898600407:ios:d04c59d714a96d6bb1b792',
    messagingSenderId: '588898600407',
    projectId: 'social-app-5c79b',
    storageBucket: 'social-app-5c79b.firebasestorage.app',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb5Nu9mtB1A6f9fff9sbUWqhFKlSCN3y0',
    appId: '1:588898600407:ios:d04c59d714a96d6bb1b792',
    messagingSenderId: '588898600407',
    projectId: 'social-app-5c79b',
    storageBucket: 'social-app-5c79b.firebasestorage.app',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4Xirudr6Zu3xjx5eYPbxPMCX5vTG5k-M',
    appId: '1:588898600407:web:e88fcc3c779ef965b1b792',
    messagingSenderId: '588898600407',
    projectId: 'social-app-5c79b',
    authDomain: 'social-app-5c79b.firebaseapp.com',
    storageBucket: 'social-app-5c79b.firebasestorage.app',
  );
}
